### ISSUE TITLE
多个查询?

### ISSUE THREAD

**Issue by trevwaddell** [Houfeng/gq-loader#2]
是否可以向.graphql文件添加多个查询

I used google translate, but I want to know if I can have 2 queries in one file. 

Thanks!

**Comment by Houfeng** [comment]
Of course, yes.

**Comment by eyasliu** [comment]
请问多个查询该怎么做，[看起来](https://github.com/Houfeng/gq-loader/blob/master/lib/index.js#L71)貌似不行
